{% set name = "radis" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radis-{{ version }}.tar.gz
  sha256: ab6b9ef2dc1ecdc8f099b2eabc3d2e6c37ee0eff

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - astropy
    - astroquery
    - beautifulsoup4 
    - cantera  
    - configparser
    - habanero
    - h5py
    - joblib  
    - lmfit  
    - matplotlib-base
    - numba  
    - pandas
    - plotly
    - psutil # to get user RAM
    - pytables # for pandas to HDF5 export
    - scipy
    - seaborn   # other matplotlib themes
    - termcolor  # terminal colors
    - specutils
    - pip
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - radis

about:
  home: https://github.com/radis/radis
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A fast line-by-line code for high-resolution infrared molecular spectra
  doc_url: https://radis.readthedocs.io/en/latest/
  dev_url: https://github.com/radis/radis


extra:
  recipe-maintainers:
    - arunavabasucom
    - erwanp
