{% set name = "radis" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radis-{{ version }}.tar.gz
  sha256: 82320a54dd1d133672ef229f4346f5b3d0a6ff5f24a017efa470d890f40ddb2e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - astropy
    - astroquery
    - beautifulsoup4 
    - cantera  
    - configparser
    - habanero
    - h5py
    - joblib  
    - lmfit  
    - matplotlib-base
    - numpy
    - numba  
    - pandas
    - plotly
    - psutil 
    - pytables 
    - scipy
    - seaborn   
    - termcolor  
    - specutils

test:
  imports:
    - radis

about:
  home: https://github.com/radis/radis
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A fast line-by-line code for high-resolution infrared molecular spectra
  doc_url: https://radis.readthedocs.io/en/latest/
  dev_url: https://github.com/radis/radis


extra:
  recipe-maintainers:
    - arunavabasucom
    - erwanp
