{% set name = "radis" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radis-{{ version }}.tar.gz
  sha256: ab6b9ef2dc1ecdc8f099b2eabc3d2e6c37ee0eff

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - astropy>=4.3.1  # Unit aware calculations
    - astroquery>=0.4.6  # to fetch HITRAN databases
    - beautifulsoup4>=4.10.0 # parse ExoMol website
    - cantera>=2.5.1   # for chemical equilibrium computations
    - configparser
#- cython          # Not needed, see #647
    - habanero>=1.2.0  # CrossRef API to retrieve data from doi
    - h5py>=3.2.1   # load HDF5
    - joblib  # for parallel loading of SpecDatabase
    - lmfit  # for new fitting modules
    - matplotlib
    - numpy
    - numba  # just-in-time compiler
    - pandas
    - plotly>=2.5.1  # for line survey HTML output
#- progressbar2    # used in vaex
    - psutil # to get user RAM
    - pytables # for pandas to HDF5 export
    - scipy>=1.4.0
    - seaborn   # other matplotlib themes
    - termcolor  # terminal colors
    - specutils
#- vaex-core>=4.17.0   # load HDF5 files  (version needed to fix https://github.com/radis/radis/issues/598)
#- vaex-hdf5
#- vaex-viz
    - pip
      - {{ pin_compatible('numpy') }}

test:
  imports:
    - radis

about:
  home: https://github.com/radis/radis
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A fast line-by-line code for high-resolution infrared molecular spectra
  doc_url: https://radis.readthedocs.io/en/latest/
  dev_url: https://github.com/radis/radis


extra:
  recipe-maintainers:
    - arunavabasucom
    - erwanp
